// Code generated by "stringer -type=Singer"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Miku-1]
	_ = x[Rin-2]
	_ = x[Len-3]
	_ = x[Lucas-4]
	_ = x[Meiko-5]
	_ = x[Kaito-6]
}

const _Singer_name = "MikuRinLenLucasMeikoKaito"

var _Singer_index = [...]uint8{0, 4, 7, 10, 15, 20, 25}

func (i Singer) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Singer_index)-1 {
		return "Singer(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Singer_name[_Singer_index[idx]:_Singer_index[idx+1]]
}
